sudo: false
language: node_js
node_js:
  - 6
  - 8
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script:
  - greenkeeper-lockfile-upload
  - npm run coveralls
